# Site settings
title: FileHelpers Library
description: The FileHelpers are a free and easy to use .NET library to import/export data from fixed length or delimited records in files, strings or streams.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.filehelpers.net" # the base hostname & protocol for your site
github_username:  MarcosMeli
libversion: "3.3.0"
libversionbig: "3.3"
author: Marcos Meli

highlighter: rouge

# Build settings
markdown: kramdown

js_dest: js

gems:
  - jekyll-seo-tag

logo: /images/filehelpers_box_small.png
image: /images/filehelpers_box_small.png

twitter:
  username: FileHelpers

exclude:  [ '*.ts',
            '*.bat',
            'Graphics',
            'README.md',
            'js/tsconfig.json',
            'oldpage',
            'OnlineWizard',
            'node_modules'
           ]
