image: Visual Studio 2019
version: 3.4.3.{build}
install:
- ps: >-
    nuget install Build\.nuget\packages.config -OutputDirectory packages

    nuget restore FileHelpers.sln
nuget:
  project_feed: true

build: off

test_script:
- ps: >-
    cd Build
    
    ./build.ps1
    
    $testFile = '.\TestResult.xml';
    $path = Resolve-Path($testFile);
    
    $url = "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)";
    
    Write-Host "Uploading '$path' to '$url'";
    $wc = New-Object 'System.Net.WebClient';
    $wc.UploadFile($url, $path);

artifacts:

- path: Output/*.nupkg
